name: KartaWorldReset
version: '${version}'
main: studio.minekarta.kartaworldreset.KartaWorldReset
api-version: 1.21
authors: [ MinekartaStudio ]
description: Reset worlds automatically in periodically
depend: ['multiverse-core']
softdepend: ['PlaceholderAPI']
commands:
  kartaworldreset:
    description: Reset World The End automatically in periodically. Help to see the manual
    aliases: kwr
    usage: Your command is not recognized. Please look at manual /kartaworldreset help
